### ISSUE TITLE
Adding the possibility of costum arrows (prev/next) on hooper navigation

### ISSUE THREAD

**Issue by Miguel-Frazao** [baianat/hooper#102]
I think this feature would be useful not just for me, costum arrows on https://baianat.github.io/hooper/examples.html#navigation-component like images, or costum classes so it can be easily manipulated. An easy way to change the default arrows/icons so we won't have to be 'restricted' to use the default ones.

**Comment by Abdelrahman3D** [comment]
You can customize navigation arrows easily, see related issue #50

**Comment by Miguel-Frazao** [comment]
Thank you
