### ISSUE TITLE
Slides are squashed on IE11

### ISSUE THREAD

**Issue by DavidRouyer** [baianat/hooper#103]
**Describe the bug**
Slides are squashed on IE11.
It's a problem with the width calculation because it's set to 0 on the slides.

**To Reproduce**
1. Go to https://baianat.github.io/hooper/examples.html with IE11

**Expected behavior**
The carousel should look right.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1556750/60173966-479ed100-9810-11e9-933f-66e7592231e6.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Internet Explorer
 - Version 11

**Comment by logaretm** [comment]
Thanks for reporting this, this is fixed in `0.2.3`.

The docs have IE11 issues due to Vuepress 1.0 not polyfilling properly but hooper should be working fine for IE11 now.

You can test it here:

https://jsfiddle.net/logaretm/wvknhzso/1/

**Comment by DavidRouyer** [comment]
The polyfills added in https://github.com/baianat/hooper/commit/26dda3e331b77d7d6576c2ca700a7ba784efaf91 were removed in https://github.com/baianat/hooper/commit/7bd674f16c45b2c42ea04d55f38da511132a1758

**Comment by logaretm** [comment]
@DavidRouyer Thanks for reporting this, fixed `0.3.1`
