### ISSUE TITLE
infiniteScroll 首次加载是从其他图闪到第一个图，是否可以优化，看上去不会闪一下

### ISSUE THREAD

**Issue by GYSky** [baianat/hooper#108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 0.0.x]

**Smartphone (please complete the following information):**
 - Version [e.g. 0.0.x]

**Additional context**

**Comment by logaretm** [comment]
I have no idea what the issue is, do you mind describing it in English?

from what I can gather you could take a look at #39
