### ISSUE TITLE
Synced  slider (centerMode: true) doesn't work as expected on newer versions.

### ISSUE THREAD

**Issue by Miguel-Frazao** [baianat/hooper#114]
I had to update my hooper due to this issue: https://github.com/baianat/hooper/issues/98.
The problem now is that my synced slider doesn't work (move) on desktop as expected, when in _**centerMode: true**_ .

Working version (0.1.5, but still with swipe issue https://github.com/baianat/hooper/issues/98): https://jsfiddle.net/vdbmj8at/11
Buggy version (0.3.2): https://jsfiddle.net/vdbmj8at/10

Both jsfiddle versions are exactly the same, except for the cdn hooper version I'm importing.

The behavior I'm expecting on synced slider is the same as my first example, version 0.1.5.

(maybe some settings had changed but didn't see/notice that on documentation)

**Comment by logaretm** [comment]
Oops, sorry about that. We changed the `sync` feature by dropping the `sync` prop in favor of a `group` prop introduced in #95  but it seems we didn't deploy the updated docs.

Here is an updated example: https://jsfiddle.net/logaretm/7guvxjay/

**Comment by Miguel-Frazao** [comment]
Sorry, your updated fiddle is still buggy, the synced slider doesn't move, how do I implement the group prop? I already tried to change "sync" for "group" bue still doesn't work: https://jsfiddle.net/pe8x3bdk/ .

**Comment by logaretm** [comment]
My bad, I forgot to save.

https://jsfiddle.net/logaretm/7guvxjay/3/

Grouping works by giving the `group` prop of the synced hoopers the same value, in my example its `g1`.
