### ISSUE TITLE
It not showing prev and next buttons

### ISSUE THREAD

**Issue by murilolivorato** [baianat/hooper#116]
Helo , do I have to set something to show next and prev buttons ?
It is not showing , thanks

**Comment by logaretm** [comment]
The next and previous buttons are an "addon" you need to import it and use it in the template, the next and prev buttons are called the "Navigation Addon".

https://baianat.github.io/hooper/getting-started.html#addons

https://baianat.github.io/hooper/examples.html#navigation-component
