### ISSUE TITLE
Nuxt?

### ISSUE THREAD

**Issue by saerose** [baianat/hooper#117]
Is it possible to create some sort of documentation on how Nuxt is implemented? Is it needed to create a plugin? Something? It's quite confusing. I read that Hooper works ok with Nuxt but I'm experiencing some issues as the carousel does not render the slides I want it to render and I don't know where the issue is because apparently my code is correct comparing it to the docs one. 😞

I can attach code if needed.

**Comment by rensite** [comment]
Nothing special, works out of a box.

Code snippet:
```
<template>
  <hooper :settings="hooperSettings" ref="carousel">
    <slide>
      <div v-for="index in 5" :key="index">
        {{index}}
      </div>
    </slide>
  </hooper>
</template>

<script>
  import { Hooper, Slide } from 'hooper'
  import 'hooper/dist/hooper.css'

  export default {
    name: 'Div',
    components: {
      Hooper,
      Slide
    },
    data() {
      hooperSettings: {
        itemsToShow: 1,
        itemsToSlide: 1
      }
    },
    methods: {
      slidePrev () {
       this.$refs.carouselPress.slidePrev();
     },

     slideNext () {
       this.$refs.carouselPress.slideNext();
     }
    }
  }
</script>
```

**Comment by logaretm** [comment]
Like @rensite said, hooper supports SSR out of the box. No need to create a plugin for it.

You might've missed importing the css, as Hooper requires some minimal CSS to work. But you will have to provide your own styles to adjust height, width, colors.

This is a sample I uploaded recently to Codesandbox: https://codesandbox.io/s/hooper-nuxt-765ot

**Comment by saerose** [comment]
Ok, thanks. I modified my slider so it's like the example but it still renders whatever the slides it wants, not the ones I want it to render, any ideas on why this would be happening?

**Comment by rensite** [comment]
> Ok, thanks. I modified my slider so it's like the example but it still renders whatever the slides it wants, not the ones I want it to render, any ideas on why this would be happening?

Could you attach the code?

**Comment by saerose** [comment]
`<template>
  <Hooper :settings="hooperSettings"
          v-if="options && options.length"
  >
    <Slide :style="{width: pWidth, height: pHeight}"
            v-for="(option, index) in options"
            :index="index"
            :key="index"
    >

      <SinglePhotoForSlider :pWidth="pWidth" :pHeight="pHeight" class="photo" :option="(option.img || option.path) + '&fit=min&q=60'" />
    </Slide>
    <Navigation slot="hooper-addons"></Navigation>
  </Hooper>
</template>

<script lang="ts">
  import {Component, Vue, Prop} from 'nuxt-property-decorator';
  import 'hooper/dist/hooper.css';
  import { Hooper, Slide, Navigation } from 'hooper';
  import SinglePhotoForSlider from "~/components/General/Sliders/SinglePhotoForSlider.vue";

  @Component({
    components: {SinglePhotoForSlider, Hooper, Slide, Navigation},
    data() {
      return {
        hooperSettings: {
          itemsToShow: 1,
          itemsToSlide: 1
        }
      }
    }
  })
  export default class HooperPhotos extends Vue {
    @Prop({ default: () => ([]) })
    options!: Array<object>;
    @Prop({ default: '190px' })
    pWidth!: String;
    @Prop({ default: '190px' })
    pHeight!: String;
  }
</script>`

Here it is

**Comment by saerose** [comment]
😔

**Comment by rensite** [comment]
Look's like the loop issue. Try to move `v-for="(option, index) in options" :index="index" :key="index"` into `SinglePhotoForSlider` as following:

```
<Slide :style="{width: pWidth, height: pHeight}">
      <SinglePhotoForSlider v-for="(option, index) in options" :index="index" :key="index" :pWidth="pWidth" :pHeight="pHeight" class="photo" :option="(option.img || option.path) + '&fit=min&q=60'" />
</Slide>
```

Hope the snippet above solves the problem ;)

**Comment by saerose** [comment]
I'm afraid that doesn't work. Images appear one on top of another (vertical). I've also tried adding the v-for to a div inside the slide, outside. Nothing works. :S For some reason it does not get the setting from the data...

**Comment by rensite** [comment]
Could you create sandbox example or provide your live project with broken hooper carousel? Gonna take a look at it. I assume it may be also css issue.

**Comment by saerose** [comment]
Here: https://codesandbox.io/s/codesandbox-nuxt-t6q72
This is no representation of what is happening to me, I can see the photos but I can not use hooper settings to modify anything. I don't know why the sandbox is behaving like that (probably I forgot something) but at least you can check the code. 🤦🏼‍♀️

**Comment by rubenmoya** [comment]
I had the same problem and it's because the hooper css is missing, inspect the page and search for the `.hooper` class, if you can't find its because of that.

In my case, it wasn't adding the CSS because I'm using [nuxt-purgecss](https://github.com/Developmint/nuxt-purgecss), adding `whitelistPatterns: [/hooper/],` fixed the problem.

I hope it helps!

**Comment by saerose** [comment]
I'm afraid css is not the problem, it is imported and i'm not using PurgeCSS or similar. Hooper class is there. Thanks anyway, I'll keep investigating. 😔

**Comment by Abdelrahman3D** [comment]
Related issue [#51](https://github.com/baianat/hooper/issues/51#issuecomment-521506679)

**Comment by alexon1234** [comment]
Thanks @saerose 

👇 This is important
> I think I figured it out. I have the sliders inside a component that has an v-show, i changed it to v-if and now it's working.
