### ISSUE TITLE
Wrong indexing in infinite scroll mode

### ISSUE THREAD

**Issue by vedmaque** [baianat/hooper#120]
**Describe the bug**
I've updgaded to 0.3.x version and infinite scroll mode seems to be broken. 

**To Reproduce**
1. Set infiniteScroll to true
2. See the generated html. Some of slides will have `is-current` class, most of them will have `is-prev` class. Indexes of 3 slides looks like this `[0, 1, 2, 0, 1, 2, -3, -2, -1]` (see screenshot)

**Expected behavior**
Expect prev slides to have `is-prev` class, next slides to have `is-next` slides.
Expect indexes like this `[-3, -2, -1, 0, 1, 2, 3, 4, 5]` for the 3 slides count

**Screenshots**
https://jmp.sh/1elHRxg

**Desktop:**
 - OS: macOS 10.14.5
 - Browser: Chrome
 - Version: 75.0

**Comment by logaretm** [comment]
Thanks for reporting this, I found the issue and fixed it. This will be available shortly in the next release.
