### ISSUE TITLE
Add ability to redraw width of hooper-slide

### ISSUE THREAD

**Issue by kylemilloy** [baianat/hooper#22]
**Is your feature request related to a problem? Please describe.**
I have a slideshow for a product. The product can show itself as a list layout or grid. This changed the height/width of the slideshow. When I switch between the two different layouts I change the container classes but I'm unable to tell hooper to update its hooper-slide widths.

**Describe the solution you'd like**
Add the ability to have `hooper-slide` recalc its width.

**Describe alternatives you've considered**
Currently I'm using a v-if/setTimeout hack to force the layout update.

**Comment by kylemilloy** [comment]
Another way to do this is to trigger resize events...this api feels a little too indirect as well.

**Comment by kylemilloy** [comment]
Code works as follows in my component:

```
watch: {
  layout() {
    setTimeout(this.redraw, 0);
  }
},
methods: {
  redraw() {
    if (typeof Event === "function") {
        window.dispatchEvent(new Event("resize"));
    } else {
        var resizeEvent = window.document.createEvent("UIEvents");
        resizeEvent.initUIEvent("resize", true, false, window, 0);
        window.dispatchEvent(resizeEvent);
    }
  }
}
```

**Comment by Abdelrahman3D** [comment]
Did you tried to use the [`hooper.updateWidth()`](https://baianat.github.io/hooper/api.html#methods) method?

**Comment by kylemilloy** [comment]
Thanks! That works great. I'd recommend we add a link directly to the API from the Readme to make this information more accessible: https://baianat.github.io/hooper/api.html

For anyone else who finds this you set it up as follows:

```jsx
<template>
    <hooper ref="hooper" />
</template>

// In your method:
this.$refs.hooper.updateWidth();
```
