### ISSUE TITLE
carry hooper-navigation out of hooper carousel

### ISSUE THREAD

**Issue by evan4** [baianat/hooper#23]
I need put ouside buttons navigations, but    css overflow: hidden; hidden buttons if set  negative positions for them. So, how can add paddings for hooper-track  or bring navigations  buttons outside of main container carousel like this 
![image](https://user-images.githubusercontent.com/6064175/51740102-eb931d80-20b4-11e9-8721-be327f59ae1d.png)

**Comment by Abdelrahman3D** [comment]
I will report this as a bug: `overflow: hidden;` should be removed from hooper main wrapper.
However, you can check examples for a custom controllers demo: https://baianat.github.io/hooper/examples.html#custom-controllers.
