### ISSUE TITLE
SCRIPT1003: Expected ':' in IE 11

### ISSUE THREAD

**Issue by oppai1232** [baianat/hooper#30]
So im getting this error when using IE 11
If you need more info, please do tell me
im using Vue cli 3

![image](https://user-images.githubusercontent.com/40618639/51975712-e02d6100-24bd-11e9-8c3a-4c64e58c5c0a.png)

**Comment by oppai1232** [comment]
![image](https://user-images.githubusercontent.com/40618639/51976680-44512480-24c0-11e9-8c56-9c2482353fd6.png)

**Comment by Abdelrahman3D** [comment]
That error because IE doesn't support object literal with a shorthand property. To solve this we add a new build addressing old browsers (<ES6 support), with [babel-plugin-transform-es2015-shorthand-properties](https://babeljs.io/docs/en/babel-plugin-transform-es2015-shorthand-properties) plugin.

**Comment by Abdelrahman3D** [comment]
fixed in the new release: https://github.com/baianat/hooper/releases/tag/v0.0.8
