### ISSUE TITLE
hooper.update() not working when adding new slides to slider

### ISSUE THREAD

**Issue by juandanceswild** [baianat/hooper#31]
**Describe the bug**
Calling `.update()` after adding slides does not update the slider.

**To Reproduce**
1. Go to https://codesandbox.io/s/34zjprk68m
2. Click on "add more items'
4. Slide through slider... the slider doesn't update.

Note: The Hooper component is implemented inside `components/HelloWorld.vue`

**Expected behavior**
After adding new slides and callling `.update()` the slider should work correctly with the new total number of slides.

**Comment by Abdelrahman3D** [comment]
Hooper doesn't handle newly added slides, however, this will be a good feature to add.

**Comment by juandanceswild** [comment]
If I may add a request as part of this feature: The current slide should persist when _prepending_ data (slides) to the array in the `v-for`

**Comment by Abdelrahman3D** [comment]
Until we completely support this here is a workaround, you use `hooper.init()` function to re-create the carousel, this will make sure the newly added slides have been added to the internal slides array, then use `hooper.update()` function to update sliders width. When adding prepend slide, the newly slides will shift the old slides index, so we can use `hooper.slideTo(currentSlide + newSlidesCount)` to update it to the previously slide.
See this draft: https://jsfiddle.net/x2ngy4mt/

**Comment by juandanceswild** [comment]
Beautiful. Thank you!
