### ISSUE TITLE
Console.log is shown when using slider

### ISSUE THREAD

**Issue by Aimho** [baianat/hooper#37]
**Describe the bug**
Console.log is shown when using slider

**To Reproduce**
1. Go to 'node_modules > hooper > dist'
2. Click on 'hooper_esm.js'
3. Scroll down to 'updateSlidesStatus(index)'
4. See 'console.log(lower, upper);'

**Expected behavior**
I hope to remove this code

**Screenshots**
![image](https://user-images.githubusercontent.com/18585277/52383887-91d02180-2abe-11e9-9de7-5eaca6653c54.png)

**Macbook Pro 15-inch:**
 - OS: Mojave 10.14.3
 - Browser chrome
 - Version

**Comment by xioten34** [comment]
Hey, remove '**console.log line 450**' in '**hooper.em.js**' file in '**hooper/dist**' folder

**Comment by Abdelrahman3D** [comment]
This has been removed in 2fb9526

**Comment by Abdelrahman3D** [comment]
fixed in new release: https://github.com/baianat/hooper/releases/tag/v0.0.8

**Comment by Aimho** [comment]
thx :)

나의 iPhone에서 보냄

2019. 2. 7. 20:27, Damien <notifications@github.com> 작성:
