### ISSUE TITLE
Following simple examples creates multiple slides

### ISSUE THREAD

**Issue by JeremyPacker** [baianat/hooper#38]
Looking into testing the basic slide example  on chrome and not sure if i'm missing something or it's broken. I am using multiple slides from the sample, but they just stack on top of each other, and they do not show up in a seperate view like the examples.

Any ideas?

` <hooper ref="carousal" @slide="updateCarousel">
                 <slide>
                    <h1>Collaborate. License Your Music. Get Discovered.</h1>
                    <p>Welcome to a new, better music company.</p>
                    <button class="">Get Started</button>
                </slide>
                <slide>
                   <h1>Collaborate. License Your Music. Get Discovered.</h1>
                   <p>Welcome to a new, better music company.</p>
                   <button class="">Get Started</button>
               </slide>
              </hooper>`

`<script>
import { Hooper, Slide, Progress as HooperProgress, Navigation as HooperNavigation } from 'hooper'

export default {
  name: 'home',
  components: {
    Hooper,
    Slide,
    HooperProgress,
    HooperNavigation
  },
  data () {
    return {
      carousalData: 0,
      hooperSettings: {
        itemsToShow: 1,
        centerMode: true,
        progress: true,
        playSpeed: 2000,
        autoplay: true
      }
    }
  },
  watch: {
    carousalData () {
      this.$refs.carousal.slideTo(this.carousalData)
    }
  },
  methods: {
    slidePrev () {
      this.$refs.carousal.slidePrev()
    },
    slideNext () {
      this.$refs.carousal.slideNext()
    },
    updateCarousel (payload) {
      this.myCarousalData = payload.currentSlide
    }
  }
}
</script>`

Thanks in advance and thank you for the great component!

**Comment by Abdelrahman3D** [comment]
you need to import stylesheet as well, as mentioned in readme.
```html
<script>
  import { Hooper, Slide } from 'hooper';
  import 'hooper/dist/hooper.css';

  export default {
    name: 'App',
    components: {
      Hooper,
      Slide
    }
  }
</script>
```

Moreover, why you use `slidePrev()`, `slideNext()`, and `updateCarousel()` methods, it's suitable only if you making an advanced use cause, triggering navigation outside `Hooper`.
