### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by cstange** [baianat/hooper#41]
Hi

I found this error:

Uncaught TypeError: Cannot read property 'style' of undefined
    at window.setTimeout (hooper.esm.js?7e04:225)

It's happen after v-if  is set false on my template using Hooper, Slide,  Navigation.

      window.setTimeout(() => {
        this.$refs.track.style.transition = '';   <----- null
        this.isSliding = false;
      }, this.$settings.transition);

**Comment by Mucaccino** [comment]
Hi. Here the same. +1

I being used them over Nuxt.js and containing a Video.js player inside, and this be working amazing... but the error was being dispatched sometimes:

![image](https://user-images.githubusercontent.com/399292/52992393-37549080-33ef-11e9-8487-5279eccd711d.png)

The comment of @cstange point to an `v-if hide` code but here instead i have an only css `display:hide`:

![image](https://user-images.githubusercontent.com/399292/52992758-7a633380-33f0-11e9-8e56-5ef335ec805d.png)

Maybe only an simple verification was solve them:

`if(this.$refs.track) this.$refs.track.style.transition = ''`

Hugs,

**Comment by hmaesta** [comment]
My console keeps logging this error on pages that do not includes Hooper.

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at VueComponent.slideTo (hooper.esm.js?7e04:250)
    at VueComponent.slideNext (hooper.esm.js?7e04:274)
    at eval (hooper.esm.js?7e04:371)
```

I am using `Hooper 0.0.6` on `Nuxt 2.0.0`/`Vue 2.5.22`.
