### ISSUE TITLE
Behavior: First show of `centerMode` without initial transition

### ISSUE THREAD

**Issue by Mucaccino** [baianat/hooper#43]
Hi, 

This issue is referred to keep more clean the first exhibition of Hoper with `centerMode:true`.

Now on the first show the slides move from initial position to centered position with an animation:

![image](https://user-images.githubusercontent.com/399292/53000811-f452e700-3407-11e9-8ac0-2dc61a3c8008.png)
![image](https://user-images.githubusercontent.com/399292/53000860-10568880-3408-11e9-90dd-9fd44292cf06.png)
![image](https://user-images.githubusercontent.com/399292/53000904-2b28fd00-3408-11e9-9855-91a7543128f4.png)

The idea of this enhancement is **make the first show of center mode in correct position or/and without transition move** instead on initial position with transition move.

Perhaps, remove the transition on beginning, or hide elements before complete position.

**Comment by Mucaccino** [comment]
Hi, 

i just implemented this behavior on my fork, using a new data `loaded:true` (who is changed at same time from event emmit `loaded`) and only input the style transition if was `loaded===true`. 

With this changes the center mode behavior is working amazing, showing centered on initialize:

![image](https://user-images.githubusercontent.com/399292/53044459-d7e79680-3469-11e9-91cb-3fc9a79482eb.png)

If want, I can make a pull request with these enhancement.

**Comment by Abdelrahman3D** [comment]
Sure, any PR(s) are welcome.

**Comment by Abdelrahman3D** [comment]
Thank you for your contribution, I've merged your pull request #46.
