### ISSUE TITLE
Error when used in production with Nuxt.js

### ISSUE THREAD

**Issue by baumannzone** [baianat/hooper#47]
**Describe the bug**
I'm working with [Nuxt](https://nuxtjs.org/).  
> package.json version: "nuxt": "^2.0.0"  

In development mode it's working fine. It's configured with 3 items and navigation arrows visible with some breakpoints, all good.  
But when I make the **build** (`npm run generate` or `npm run start`) for production the website crashes and slider is not working anymore.

Slider is not working and it's showing 2 only because the javascript error.  Images are missing, and slider items width/height is wrong. Navigation arrows are broken too.

Error message:
```
Uncaught (in promise) TypeError: Cannot assign to read only property 'message' of object ''
    at 94653d717eea14401790.js:1 
```

**To Reproduce**
1. `npm run generate` with nuxt
2. Open generated page in `/dist`
3. See error

**Expected behavior**
Render the slider fully functional with 3 images by default and the navigation arrows working.

**Screenshots**

![image](https://user-images.githubusercontent.com/5422102/53088803-1c773e80-350b-11e9-89bc-ba5a66443043.png)

**Desktop (please complete the following information):**
- Node: Tested with `v8`, `v10` and `v11`
 - OS: OSX
 - Browser: Chrome
 - Version: 72.0.3626.109 (Build oficial) (64 bits)

**Additional context**

**Comment by Mucaccino** [comment]
Hi,

I have using Hooper over Nuxt.js and hosting on a static server with `npm run generate` and local development with `npm run dev` and here I have never seen this error dispatched.

Anyway, the error say that an read only property `message` not be setted, and the Hooper code not have anyone reference to this property `message`... @baumannzone maybe be an problem in your side code.

Hugs,

**Comment by baumannzone** [comment]
Can you share / show me your code?

How are you using it? I've been investigating and I realized it may be becauseI've a wrong nuxt config (related to plugins block)

Thanks for the quick reply!

**Comment by Abdelrahman3D** [comment]
@baumannzone please share your working code, so we can help you debug your issue.

**Comment by baumannzone** [comment]
Yes, sure. Here is my repo (branch: `feat/update-nuxt`):  
https://github.com/OSWeekends/osweekends.github.io/tree/feat/update-nuxt

Project is inside `/src`

**Comment by Mucaccino** [comment]
Good, I was tell if you want to share your code or snippet of it, but @Abdelrahman3D has already do.

@baumannzone, have you tried checking at what time this error is firing by clicking on the console error? Have you tried searching for the `message` String in your code, to see if you even refer to it yourself?

Anyway, we can now give you some help by taking a look at your shared code.

**Comment by baumannzone** [comment]
Hi, I clicked in the error, but it's minimized / ofuscated code, so it is weird.

As I know, I think the problem is because I'm missing how nuxt 3rd party libraries works. I made it work with other slider library, but I had to add some config to `nuxt.config.js` file and some other plugin settings.

If you could share your nuxt config file where you are using **Hooper** would be sufficient for me.

Thanks you both.

**Comment by Mucaccino** [comment]
Hi, 

I guess that error is more vinculated to Nuxt.js instead Hooper.

So, I forked your project and clicking on console error (and using Chrome Dev to unminimize) I see that:

![image](https://user-images.githubusercontent.com/399292/53130528-536c4500-3549-11e9-8dca-507e0f83ac0c.png)

Searching on web I found a lot of recent issues to a newest version of Nuxt.js, and one of that was marked with `cmty:bug-report`:

https://github.com/nuxt/nuxt.js/issues/5056

So, maybe you can post your issue there too.

Hugs,

**Comment by baumannzone** [comment]
Yes, that's the problem. But it does says noting to me. I'm still investigating.

If you have used Nuxt & Hooper, can you show the code?
Regards

**Comment by baumannzone** [comment]
Maybe you could add a section in the **docs** where you show how to configure it to be used with Nuxt

**Comment by Mucaccino** [comment]
Hi @baumannzone, how's it going?

So, i was tracking the error and really has another error that dispatch this `message` _Nuxt.js_ error...

![image](https://user-images.githubusercontent.com/399292/53367302-87b67b80-3924-11e9-9cde-f1f2c7d54f62.png)

![image](https://user-images.githubusercontent.com/399292/53367415-e4199b00-3924-11e9-938f-399200813e25.png)

`"Failed to execute 'appendChild' on 'Node': This node type does not support this method."`

The `appendChild` has tree ocorrences on Hooper, and with this information maybe we can be capable to say  it could be fixed on Hooper side... look at the `apendChild` on _init clones_ flow:

![image](https://user-images.githubusercontent.com/399292/53367722-a8cb9c00-3925-11e9-9570-bf8182d9f3d6.png)

Then maybe anything can be done... About the docs, mine Nuxt.js + Hooper usage looks like your implementation, no real difference.

**Comment by baumannzone** [comment]
Ok, is fine, thanks anyway.

**Comment by Mucaccino** [comment]
@baumannzone, you solve them?

**Comment by baumannzone** [comment]
No, I didn't. I just stopped using Hooper. Couldn't find a solution.

**Comment by bart** [comment]
I have the exact same error on Netlify. Any solution to this?

**Comment by baumannzone** [comment]
> I have the exact same error on Netlify. Any solution to this?

I couldn't find a solution so I stopped using Hopper.

**Comment by bart** [comment]
I figured it out. You just have to clear cache and local storage. It has to do with the auth module.

**Comment by baumannzone** [comment]
> I figured it out. You just have to clear cache and local storage. It has to do with the auth module.

Can you show your code?

**Comment by bart** [comment]
It has nothing to do with your code. Just clear browser cache + local storage.

**Comment by baumannzone** [comment]
I don't understand why you guys are so scared to show the code..

**Comment by bart** [comment]
We are not scared but it has nothing to do with my code dude. So that won't help you.

**Comment by nachiomdq** [comment]
Hi, sorry for comment in this old post, but i found the solution here (if you are using purgeCSS)

https://github.com/baianat/hooper/issues/117#issuecomment-522589606
