### ISSUE TITLE
Easy way to click and select the slide

### ISSUE THREAD

**Issue by shadowam** [baianat/hooper#48]
Is there any chance of providing an option to click on a slide and set it as currentSlide?

I'm currently showing itemsToShow=12 from 40 total items and would like to click on one of them and make it the currentSlide, making it slide to the center (with 'centerMode', of course).

**Comment by Abdelrahman3D** [comment]
You can implement this use cause easily, by adding an event listener on each slide when it is clicked, update Hooper using [`slideTo`](https://baianat.github.io/hooper/api.html#hooper-slideto-index) method, and pass the slide index to it.

**Comment by fateme572** [comment]
> You can implement this use cause easily, by adding an event listener on each slide when it is clicked, update Hooper using [`slideTo`](https://baianat.github.io/hooper/api.html#hooper-slideto-index) method, and pass the slide index to it.

how can i do this?? im using click event on slide but its not defined and dosen't work. and i cant emit click event in hooper.js and i don't access to template of slide... how can i resolve this problem?

**Comment by ratPersona** [comment]
I had this issue and I put the @click event on the internal div, example:

```
          <slide class="button" v-for="number of slideNumbers" :key="number">
            <div @click="carouselButton()">{{ number }}</div>
          </slide>
```

**Comment by SarccoCZL** [comment]
> You can implement this use cause easily, by adding an event listener on each slide when it is clicked, update Hooper using [`slideTo`](https://baianat.github.io/hooper/api.html#hooper-slideto-index) method, and pass the slide index to it.

Can you link some video or code how to do that? im stucked on this for 3 days :(

**Comment by ismail9k** [comment]
Please check this: https://codepen.io/ismail9k/pen/MWXaqmj
