### ISSUE TITLE
Infinite Scroll loses click handlers

### ISSUE THREAD

**Issue by uncleramsay** [baianat/hooper#49]
**Describe the bug**
When using infinite scroll, the slides are duplicated to ensure there are always slides on the screen.
If you put an `@click` handler on the contents of a slide, it only works on the original element, not the duplicated one

**Expected behavior**
Click events should be retained

**Screenshots**
Original element has the handler:
![image](https://user-images.githubusercontent.com/10271207/53174367-8f52e900-35e1-11e9-890f-20b0f26ea147.png)
Duplicated element does not:
![image](https://user-images.githubusercontent.com/10271207/53174399-a265b900-35e1-11e9-8bef-1c8a3e7c2c9c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 0.0.8

**Comment by Mucaccino** [comment]
Really, Hooper use default `cloneNode` and this clone only DOM and not event listeners.

**Comment by uncleramsay** [comment]
This is still a bug that needs fixing...
