### ISSUE TITLE
Allow setting title of arrow icons in Navigation.vue

### ISSUE THREAD

**Issue by anachronic** [baianat/hooper#50]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but the website I'm building is in spanish, and the title of the generated svgs for navigation are "Arrow Left" and "Arrow right", which are not really convenient for me.

**Describe the solution you'd like**
Well, of course the best solution for this would be internalization, but seeing that is very ambicious, I'd be happy passing a prop or something like that to the navigation component indicating the title the arrows should have.

**Describe alternatives you've considered**
I guess I could create my own component and use that instead, but it seems like it would be better to simply implement this upstream. I'm sure other people could benefit from it

**Additional context**
Nothing really, I'm just building a website that needs a carousel and is in spanish.

**Comment by ismail9k** [comment]
You can pass your custom icons to the navigation component it will overwrite the default icons.

Example
```html
  <hooper>
    <slide>
      slide 1
    </slide>

    <hooper-navigation slot="hooper-addons">
      <svg slot="hooper-prev">
        <path d="..." />
      </svg>
      <svg slot="hooper-next">
        <path d="..." />
      </svg>
    </hooper-navigation>
  </hooper>
```

Vue  2.6.0+
```html
  <hooper>
    <slide>
      slide 1
    </slide>

    <hooper-navigation v-slot:hooper-addons>
      <svg v-slot:hooper-prev>
        <path d="..." />
      </svg>
      <svg v-slot:hooper-next>
        <path d="..." />
      </svg>
    </hooper-navigation>
  </hooper>
```

**Comment by anachronic** [comment]
Works, thanks for the help!

**Comment by fateme572** [comment]
can we use things other than <svg>?? like icons

**Comment by Abdelrahman3D** [comment]
You can use font-icons instead of SVGs.

**Comment by fateme572** [comment]
how can i do that?I'm trying to put `<span class="my-icon" v-slot:hooper-prev>`  instead of `<svg>` but just show initial icons again.

**Comment by ExiaGo** [comment]
> how can i do that?I'm trying to put `<span class="my-icon" v-slot:hooper-prev>` instead of `<svg>` but just show initial icons again.

@fateme572  I think you should check your version of vue, you can try like below.
`<span class="my-icon" slot="hooper-prev">`
