### ISSUE TITLE
Please correct the ending <template> tag in the documentation

### ISSUE THREAD

**Issue by MoloF** [baianat/hooper#53]
Since I was a novice and tried to install this component myself, I ran into a problem and for a long time understood about its elimination. The way to solve it was very simple, it was necessary to fix the ending <template> tag with </template>, so please correct this error in the documentation. Thank.

https://github.com/baianat/hooper#use-hooper

**Comment by Abdelrahman3D** [comment]
Oh, thanks for making us pay attention.
