### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by daav7713** [baianat/hooper#55]
Im trying to sync to sliders but its not working and in the console this message is show 
Hooper: expects an element with attribute ref="myCarousel2", but found none.

`              <hooper sync="myCarousel2" ref="carousel" @slide="updateCarousel">
                      <slide>
                        slide 1
                      </slide>
                      <slide>
                        slide 2
                      </slide>
                    </hooper>
                    <hooper ref="myCarousel2" :itemsToShow="3" :centerMode="true">
                      <slide>
                        slide 1
                      </slide>
                      <slide>
                        slide 2
                      </slide>
                    </hooper>`

That's my code, any help please?

**Comment by Abdelrahman3D** [comment]
I can't know why it doesn't work for you, maybe it's something related to your workflow, hover here's a working example you can test yourself: [example](https://jsfiddle.net/Abdelrahman3d/cxh2mopf/2/), or you can see the [docs](https://baianat.github.io/hooper/examples.html#sync)
