### ISSUE TITLE
Style different for item of middle

### ISSUE THREAD

**Issue by joelsantosbr** [baianat/hooper#59]
I'm trying to use the @slideAfter method to capture the items with the isActive class and put a different style in the middle item, for example, whenever three `itemsToShow: 3` ​​slides are displayed, the middle item gets bigger than the others

**class `active` in the middle item**

![slide-item-middle](https://user-images.githubusercontent.com/12235718/54999122-59bd6900-4fae-11e9-8fb3-ad0cb478a1d6.png)

**Comment by Abdelrahman3D** [comment]
This is a good feature to be implemented, we will add a statue class to the currently active slide.
