### ISSUE TITLE
Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by brunosilvafranca** [baianat/hooper#6]
Sorry my english!

When you use the infiniteScroll: true, and you have a slide, the slide is cloned normally, but when you move the slide it returns this error.

![captura de tela_20190105204515](https://user-images.githubusercontent.com/39228171/50730013-de74b580-112a-11e9-972f-2c86a9f1025d.png)
![captura de tela_20190105204528](https://user-images.githubusercontent.com/39228171/50730014-de74b580-112a-11e9-92ee-7df6c266c88c.png)

**Comment by Abdelrahman3D** [comment]
Hello, please provide me with your working code snippets, or an online demo, so I can help you debugging this issue.

**Comment by brunosilvafranca** [comment]
In codesandbox
https://codesandbox.io/s/o7qz5pzzoz
