### ISSUE TITLE
Option to customize hooper css classes

### ISSUE THREAD

**Issue by waghcwb** [baianat/hooper#60]
**Is your feature request related to a problem? Please describe.**
It will be nice if we can customize the `hooper` css classes.

**Describe the solution you'd like**
A new prop to customize the css classes.

**Comment by Abdelrahman3D** [comment]
I didn't understand your feature request exactly, can you please provide a use case for this feature, so we can better understand it.

**Comment by BokangThoola** [comment]
seems like no css, whats the problem

**Comment by remarks** [comment]
Possibly having multiple sliders on the same page with different styles.

**Comment by ConceptCodes** [comment]
how can i adjust the height of the hooper slide, i added a custom css element to the slide but it doesn't effect height

**Comment by Abdelrahman3D** [comment]
Select `.hooper-slide` class and apply your style to it, check this [demo](https://jsfiddle.net/7jh5ozbv/2/).

**Comment by francoism90** [comment]
@Abdelrahman3D Thanks for the demo. :)
