### ISSUE TITLE
How to display half of previous slide

### ISSUE THREAD

**Issue by waghcwb** [baianat/hooper#61]
**Describe the bug**
This is not a bug itself, in the docs we can see how to show half of the next slide by setting `itemsToShow` prop to `1.25` for example. But I want to know how can I show half of the previous slide after scrolling the first one.

I want to achieve the following effect, taking a slider with 4 slides:
- **First slide:** Half of the second slide is shown.
- **Second and Third slide:** Half of the previous and half of next slide is shown.
- **Last slide**: Only half of the previous slide is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/6169950/55033533-2997b980-4ff2-11e9-9309-8eede12d30e6.png)

**Comment by Abdelrahman3D** [comment]
You can try `centerMode="true"` and `itemsToShow="2"`, see [examples](https://baianat.github.io/hooper/examples.html#center-mode) in the documentions.

**Comment by waghcwb** [comment]
@Abdelrahman3D,

Awesome, that worked. Thank you.
