### ISSUE TITLE
Slide looses "index" prop value

### ISSUE THREAD

**Issue by filipepina** [baianat/hooper#67]
**Describe the bug**
Slide looses "index" prop value after adding or removing slides.

**To Reproduce**
https://codesandbox.io/s/644pkk7y0z

After changing the number os slides, the slides loose their index, making the is-active and is-current classes not being properly set.
Basically, this setter stops working (https://github.com/baianat/hooper/blob/master/src/Hooper.vue#L285), leaving the index with the default value of 0

**Expected behavior**
It would be expected for the slider to get the current index so that the classes is-active and is-current get correctly applied

**Comment by filipepina** [comment]
I've added a quick fix using slide element attributes, but didn't made a pull request as it's a really lousy fix. I'm sure there's a better way to change props on the child component.
https://github.com/filipepina/hooper/

**Comment by Abdelrahman3D** [comment]
Thank you for reporting, we will fix it very soon.
