### ISSUE TITLE
Slider with preview on the sides

### ISSUE THREAD

**Issue by Zyles** [baianat/hooper#68]
Can this slider do this: http://ironwolf.com/

Showing a previous and next image on the left and right, which are clickable but faded out.

**Comment by filipepina** [comment]
Hi @Zyles,

Yes, it can. For example, you can set it up for showing 3 items and the current slide will have a "is-current" class that you can set with "opacity: 1", while the rest of the slides would get "opacity: 0.5".

But beware, if you dynamically change the slides or the the slider options, you'll get the problem I mentioned on issue #67 

Hope it helps :)

**Comment by Abdelrahman3D** [comment]
As @filipepina said you can lower the opacity for all the slides, but the current one. here is a working [demo](https://jsfiddle.net/7jh5ozbv/2/)

**Comment by Zyles** [comment]
> As @filipepina said you can lower the opacity for all the slides, but the current one. here is a working [demo](https://jsfiddle.net/7jh5ozbv/2/)

Ok thanks, that kinda works but there seems to be an issue with the demo.

I am unable to click the left or right slide to change it. It works well with my mouse wheel.

Is that a bug or is there more settings needed?

**Comment by filipepina** [comment]
@Zyles Check issue #48 :)
You just need to add a click listener to call slideTo()
