### ISSUE TITLE
Sync not working inside vuetify VCard

### ISSUE THREAD

**Issue by aldarund** [baianat/hooper#69]
**Describe the bug**
If hooper put inside vuetify VCard it cant resolve ref and so sync not working

**To Reproduce**
https://codesandbox.io/s/m5v6zpvyjy
Hooper: expects an element with attribute ref="hooper2", but found none.

**Expected behavior**
Sync working

Work fine if put outside of VCard element

Init happens in mounted,

https://github.com/baianat/hooper/blob/master/src/Hooper.vue#L467

but `Note that mounted does not guarantee that all child components have also been mounted.`

https://vuejs.org/v2/api/#mounted

So then refs got undefined in init because its not in nextTick

**Comment by aldarund** [comment]
@Abdelrahman3D its still not working in 0.1.5 
https://codesandbox.io/s/l2844n1wnl

**Comment by Abdelrahman3D** [comment]
Okay, let's reopen this issue for now, and make more investigations on this.

**Comment by aldarund** [comment]
Not really specific to VCard, right now i have it just inside vuetify layout components and it fails too. VCard just easiest for reproduction
