### ISSUE TITLE
Every slide item has same class **hooper-slide is-active is-current**

### ISSUE THREAD

**Issue by trank2012** [baianat/hooper#70]
**Describe the bug**
Every slide item has same class **hooper-slide is-active is-current**

**To Reproduce**
 ```
<slide v-for="(element, indx) in contentSection" :key="indx">
 slide content
</slide>
```
**Screenshots**
http://prntscr.com/ng75zw

**Desktop:**
 - OS: Windows
 - Browser:  Chrome
 - Version 73.0.3683.103

**Additional context**
Full code

```
<template>
<hooper :settings="hooperSettings" ref="hooper">
  <slide v-for="(element, indx) in contentSection" :key="indx">
       {{element.content}}
  </slide>
  <hooper-navigation slot="hooper-addons">
    <button slot="hooper-next">
      <i class="far fa-chevron-right"></i>
     </button>
     <button slot="hooper-prev">
        <i class="far fa-chevron-left"></i>
      </button>
    </hooper-navigation>
</hooper>
</template>
export default {
  data () {
    return {
      hooperSettings: {
        wheelControl: false,
        mouseDrag: false,
        transition: 600,
        centerMode: true
      }
    }
  },
  components: {
    Hooper,
    Slide,
    HooperNavigation
  }
}
```

**Comment by filipepina** [comment]
It's the same issue described here: #67 
You can use this temporary solution (https://github.com/filipepina/hooper/) and assign a "slideIndex" attribute to each slide.

**Comment by trank2012** [comment]
> It's the same issue described here: #67
> You can use this temporary solution (https://github.com/filipepina/hooper/) and assign a "slideIndex" attribute to each slide.

I see. Thanks for information, didnt see previous issue.
