### ISSUE TITLE
How to use v-for inside <slide> ?

### ISSUE THREAD

**Issue by fiandimas** [baianat/hooper#74]
i was getting error when using looping inside \<slide> the error say Missing required prop: "index"

**Comment by Abdelrahman3D** [comment]
Can you please provide me with your working code example, moreover, when you work with dynamic slides, it's recommended to path slide index as a prop for each slide. [docs](https://baianat.github.io/hooper/getting-started.html#dynamic-slides)

**Comment by fiandimas** [comment]
sorry sir, i dont know about the doc, thanks very much. but it still get error. my code same with the doc `<slide v-for="(result, indx) in products" :key="indx" :index="indx">
              {{ result }}
</slide>` which products is array. here is the errors
![image](https://user-images.githubusercontent.com/38910922/56963840-201ae780-6b84-11e9-82b4-7e89df60b544.png)

**Comment by Abdelrahman3D** [comment]
It's hard to know the issue that way, can you provide me with your working code snippet?

**Comment by fiandimas** [comment]
slide
![image](https://user-images.githubusercontent.com/38910922/57009151-14303380-6c1f-11e9-8526-d1e09313a1e1.png)

**Comment by Abdelrahman3D** [comment]
Please share how you get the products array, in text format.

**Comment by fiandimas** [comment]
i parse result api to products in mounted

**Comment by Abdelrahman3D** [comment]
You got this issue because the products array is not generated when Hooper slider created.
You can fix this using two methods:
* hide the craousel until you get the products,
```html
<hooper :settings="hooper"  v-if="products && products.length">
...
</hooper>
```

* show a place holder slides until you got the products.
```html
<hooper :settings="hooper">
    <!-- main slides -->
    <template v-if="products && products .length">
      <slide v-for="(slide, indx) in products" :key="indx" :index="indx">
        {{slide}}
      </slide>
    </template>

    <!-- placeholder slides -->
    <template v-else>
      <slide v-for="(slide, indx) in 3" :key="indx" :index="indx">
      </slide>
    </template>
</hooper>
```

**Comment by fiandimas** [comment]
thank you sir, its work

**Comment by curryhh** [comment]
> You got this issue because the products array is not generated when Hooper slider created.
> You can fix this using two methods:
> 
> * hide the craousel until you get the products,
> 
> ```
> <hooper :settings="hooper"  v-if="products && products.length">
> ...
> </hooper>
> ```
> 
> * show a place holder slides until you got the products.
> 
> ```
> <hooper :settings="hooper">
>     
>     <template v-if="products && products .length">
>       <slide v-for="(slide, indx) in products" :key="indx" :index="indx">
>         {{slide}}
>       </slide>
>     </template>
> 
>     
>     <template v-else>
>       <slide v-for="(slide, indx) in 3" :key="indx" :index="indx">
>       </slide>
>     </template>
> </hooper>
> ```

Thank you first. It's not wrong now, but it can't slide and it won't play automatically
setting：<hooper  v-if="bannerData && bannerData.length" :playSpeed="500" :itemsToShow="1.1" :centerMode="true" :infiniteScroll="true" :touchDrag="true">  
bannerData There's no problem with my data，Now the console has no error, can't slide or play automatically.
