### ISSUE TITLE
Add ability to turn component on and off

### ISSUE THREAD

**Issue by gskgrek** [baianat/hooper#79]
I.e. I have 5 elements that i want to behave responsively (wrap, etc.) when window is wider than some breakpoint and start using hooper only when window width is smaller than breakpoint.

Either property or method to invoke.

**Comment by Abdelrahman3D** [comment]
You can achieve this using Vue and [Window​.match​Media()](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), for instance, see this snippet:

```html
<template>
  <template v-if="isMobile">
    <hooper>
      ...
    </hooper>
  </template>
 
  <template v-else>
    <!-- add your code here -->
  </template>
<template>

<script>
export default {
 ...
  computed: {
    isMobile() {
      return window.matchMedia('(max-width: 600px)');
    }
 }
 ...
}
</script>
```

**Comment by Abdelrahman3D** [comment]
A working [example](https://jsfiddle.net/Abdelrahman3d/jq9mwoxz/25)
