### ISSUE TITLE
Section tag global styles affect unintentionally hooper component styles

### ISSUE THREAD

**Issue by gskgrek** [baianat/hooper#80]
If i set global style in my app:
```
section{
    min-height: 100vh;
    padding-top: 100px;
}
```
than slider also takes this styles and don't resets them.
Solution would be to use more neutral `<div>` instead of `<section>` as wrapper.

**Comment by DavidRouyer** [comment]
@gskgrek `<section>` is fine. Fix your CSS. You should never apply this kind of rules to all of your `<section>` tags. Use a class.
