### ISSUE TITLE
shortDrag=false isn't a solution

### ISSUE THREAD

**Issue by Arredatore** [baianat/hooper#84]
**Describe the bug**
When scrolling slider triggered

**To Reproduce**
Start scroll, the slider will trigger.

**Expected behaviour**
The slider will not trigger.

**Additional context**
I like your slider, it simple and flexible in the same but the touching needs a tuning. This is what I'm trying to do [https://pastiche.design/catalogue-v2](https://pastiche.design/catalogue-v2) there a few sliders on the page and they trigger each time one touch the screen.

**Comment by batFormat** [comment]
+1 same issue

**Comment by Abdelrahman3D** [comment]
`shortDrag` is related to dragging event not scrolling. Maybe what you are looking for is `wheelControl`, try to set it false.

**Comment by Abdelrahman3D** [comment]
@batFormat @Arredatore can you please give me a feedback, whether this fixed your issue or not?

**Comment by Arredatore** [comment]
Excuse me, no this doesn't help.
I will reproduce this on codesandbox tomorrow

**Comment by Abdelrahman3D** [comment]
It will be closed due to no further activity occurs.

**Comment by gafuri** [comment]
Happened to me. 

**How to reproduce**
Open the hooper carousel on any touch device.
And vertical scroll the page over the carousel.

**Current behaviour**
The carousel slightly moves left/right while scrolling the page.

**Expected behaviour**
Page scroll without affecting the carousel.

Settings:
```
{
        wheelControl: false,
        shortDrag: false, // Doesn't solve the problem
        mouseDrag: false,
        touchDrag: true 
}
```

**Comment by Arredatore** [comment]
Thank you for doing that animation. Yes, that is exactly what I see on my page.

**Comment by Arredatore** [comment]
I'm hard working on another project right now, but I'm still interested in this.

**Comment by rensite** [comment]
> I'm hard working on another project right now, but I'm still interested in this.

Consider Vue-slick component. It works flawless! 🥇

**Comment by logaretm** [comment]
Sorry guys it took a while to address this, currently, I'm the only one maintaining our OSS @baianat

Anyways I have submitted a [PR that seems to fix this](https://github.com/baianat/hooper/pull/118) when I tested it against @rensite example.

**Comment by Arredatore** [comment]
Vue CLI doesn't see the update should I update manually?

**Comment by logaretm** [comment]
This isn't live yet, I might do a quick release later today. There seem to be a couple of issues to iron out. If you want you could checkout the branch and use that version instead.

**Comment by Arredatore** [comment]
Thank you, I'll wait. By the way, maybe of top, but the same issue is typical for image compare plugins.

**Comment by logaretm** [comment]
Hooper `0.3.3` is out with this update, let me know if it was fixed or improved as I guess there would be some cases to iron out.

**Comment by Arredatore** [comment]
Thank you, everything works as it should!

**Comment by rabetz** [comment]
I tested it and same results yet !
