### ISSUE TITLE
Mouse drag does not stop when reached last slide

### ISSUE THREAD

**Issue by 2503shubham** [baianat/hooper#86]
**Describe the bug**
 Suppose you have more than 8 slides in hooper and items to show is 4, when you drag through the mouse, it does not stop at last slide, that is 8th slide.. it stops at 10 position which is empty

**Expected behavior**
mouse/touch drag and nextClick also should stop at it's last element

**Comment by Abdelrahman3D** [comment]
Related issue #85

**Comment by Abdelrahman3D** [comment]
Feature added in #90
