### ISSUE TITLE
Does this work with IE6,7,8,9 etc?

### ISSUE THREAD

**Issue by UnaOmnia** [baianat/hooper#87]
Just wondering the compatibility. Says the latest but that doesn't tell me how far back it is compatible. So what do you think?

**Comment by logaretm** [comment]
You can assume it has the same compatibility level as Vue, from [the docs](https://vuejs.org/v2/guide/installation.html):

> Vue does not support IE8 and below ...

As for IE9, I think it works fine. The docs in the example, however, have styling issues with IE9.
