### ISSUE TITLE
Hooper images not show when bind with vue 

### ISSUE THREAD

**Issue by Olti-B** [baianat/hooper#93]
**Hooper images not show when bind with vue **
I am using hooper with vue 
like in this example 
   
       <hooper :key="hopper_key" :progress="true" :infiniteScroll="true">
            <slide>
              <img :src="detail_data.poi_simg_src" alt>
            </slide>
            <hooper-progress slot="hooper-addons"></hooper-progress>
          </hooper>

And when i run it shows shows nothing
The hooper html produced is 
![hooper_html](https://user-images.githubusercontent.com/36789108/59550183-2e706780-8f68-11e9-9797-c5dc744dbbd9.PNG)

*** Environment tested  ***
Chrome v.75

**Comment by Abdelrahman3D** [comment]
Can you provide us with a working example, so we can debug your issue?

**Comment by Olti-B** [comment]
Hej @Abdelrahman3D  i created a sand box 
https://codesandbox.io/s/vue-template-kvrlp?fontsize=14

**Comment by Abdelrahman3D** [comment]
Thanks, @Olti-B, at first glance I noticed that you forgot to include `Hooper`'s stylesheet. A quick fix for this is to import the CSS file at the first of your file `import 'hooper/dist/hooper.css';`.
This seemed to be a common issue, form our side we will emphasize it more in the docs, or maybe include the styles with the JavaScript file.
