### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [baianat/hooper#96]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/baianat/hooper/blob/master/package.json#L30

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

Same for `path` (https://nodejs.org/api/fs.html).

**Comment by logaretm** [comment]
Thanks for catching this! `util` was also there.
