### ISSUE TITLE
Error in created hook: "TypeError: Cannot read property 'filter' of undefined"  found in  ---> <Hooper>

### ISSUE THREAD

**Issue by curryhh** [baianat/hooper#99]
**Describe the bug**

![微信图片_20190623204043](https://user-images.githubusercontent.com/22719549/59976481-c240d400-95f7-11e9-88bb-58d394ae429f.png)
![微信图片_20190623204145](https://user-images.githubusercontent.com/22719549/59976506-09c76000-95f8-11e9-9e92-834a1fd84784.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 0.0.x]

**Smartphone (please complete the following information):**
 - Version [e.g. 0.0.x]

**Additional context**

**Comment by curryhh** [comment]
What's the problem?How to solve it?

**Comment by Abdelrahman3D** [comment]
This could be because there are no slides see related issues #74, if not can you please provide me with a working example, so I can help you debug this issue.

**Comment by andreassoegaard** [comment]
I solved the issue by adding some slides, as proposed by @Abdelrahman3D

**Comment by logaretm** [comment]
I tested this against #104 and it looks like it would fix it.

**Comment by curryhh** [comment]
`<template>
    <hooper  v-if="bannerData && bannerData.length" :playSpeed="500" :itemsToShow="1.1" :centerMode="true" :infiniteScroll="true" :touchDrag="true">
        <slide v-for="(item,index) in bannerData" :key="index">
          <a :href="item.jump_url">
            <img :src="item.image_url" :alt="item.title">
          </a>
        </slide>
         <hooper-pagination slot="hooper-addons"></hooper-pagination>
    </hooper>
</template>

<script>
  import { Hooper, Slide, Pagination as HooperPagination  } from 'hooper';
  import 'hooper/dist/hooper.css';
  // import {Toast} from'vant'
  export default {
    components: {
      Hooper,
      Slide,
      HooperPagination 
    },
    data(){
      return{
        bannerData:[],
      }
    },
    mounted(){
      this.banner();
    },
    methods:{
      banner(){
        this.$api.home.banner().then(res => {
            this.bannerData=res
            // this.hooper.update()
          //  console.log(this.bannerData);
          }).catch(error =>{
           
            console.log('error',error)
              //弹窗返回错误信息
            //  Toast(error.msg);  
        })
      },
    }
  }
</script>
<style lang="scss" scoped>
.hooper-slide .is-current {
  transform: scale(1);
}
.hooper{
    height: 300px;
    width: 100%;
    display: inline-block;
    .hooper-slide{
        height: 100%;
        width: 100%;
        padding: 5px;
        display: inline-block;
    }
    
}

</style>`

**Comment by curryhh** [comment]
Now the console has no error, can't slide or play automatically
